# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ "main", "master" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'imgs/**'
      - 'LICENSE*'
      - '.gitignore'
  pull_request:
    branches: [ "main", "master" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'imgs/**'
      - 'LICENSE*'
      - '.gitignore'

jobs:
  fmt:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --check

  clippy:
    name: Clippy Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy -- -D warnings

  test-ina238:
    name: INA238 Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --test tests_ina238 --verbose
    
            #  Optional Cleanup
      - name: Remove artifacts from target
        run: cargo clean --verbose

  test-ina239:
    name: INA239 Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --test tests_ina239 --verbose
    
            #  Optional Cleanup
      - name: Remove artifacts from target
        run: cargo clean --verbose